export const STRING = {
  HEADING: "Unlimited movies, TV shows and more",
  SUBHEADING: "Watch anywhere. Cancel anytime.",
  PARA: "Ready to watch? Enter your email to create or restart your membership.",
  FOOTERHEADING: "Questions? Call",
  FOOTERNUMBER: "000-800-919-1694",
  COL1ROW1: "FAQ",
  COL1ROW2: "Investor Relations",
  COL1ROW3: "Privacy",
  COL1ROW4: "Speed Test",
  COL2ROW1: "Help Centre",
  COL2ROW2: "Jobs",
  COL2ROW3: "Cookie Preferences",
  COL2ROW4: "Legal Notices",
  COL3ROW1: "Account",
  COL3ROW2: "Ways to Watch",
  COL3ROW3: "Corporate Information",
  COL3ROW4: "Only on Netflix",
  COL4ROW1: "Media Centre",
  COL4ROW2: "Investor Relations",
  COL4ROW3: "Terms of Use",
  COL4ROW4: "Contact Us",
  NETFLIXINDIA: "Netflix India",
  SIGNIN: "Sign In",
  GETSTARTED: "Get Started",
  ENGLISH:"English",
  HINDI:"हिंदी",
  EMAIL :"Email address",
  TITLE:"Go to Footer",
  LOGO: "Netflix Logo",
};
